export enum OrderStatus {
    orderCreated = 'order-created',
    onOrderCompleted = 'on-order-completed',
    paymentPending = 'payment-pending',
    waitingForOrderAuthorization = 'waiting-for-order-authorization',
    approvePayment = 'approve-payment',
    paymentApproved = 'payment-approved',
    requestCancel = 'resquest-cancel',
    waitingForSellerDecision = 'waiting-for-seller-decision',
    authorizeFulfillment = 'authorize-fulfillment',
    orderCreateError = 'order-create-error',
    orderCreationError = 'order-creation-error',
    windowToCancel = 'window-to-cancel',
    readyForHandling = 'ready-for-handling',
    startHandling = 'start-handling',
    handling = 'handling',
    invoiceAfterCancellationDeny = 'invoice-after-cancellation-deny',
    orderAccepted = 'order-accepted',
    invoice = 'invoice',
    invoiced = 'invoiced',
    replaced = 'replaced',
    cancellationRequested = 'cancellation-requested',
    cancel = 'cancel',
    canceled = 'canceled',
}